[package]
authors = ["Brandon Matthews <bmatthews@zipcar.com>"]
name = "elatec-multitec-nano-simple"
version = "0.1.0"

[dependencies]
bitflags = "1.0.3"
byteorder = { version = "1.2.3", default_features = false }
embedded-hal = "0.2.1"
nb = "0.1.1"
